package io.github.josemodi97.sageactive4j.scaffold;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

/**
 * Shared by both plugin builds (each adds this directory to its test
 * sources), so each proves the templates load from its own packaging.
 */
class ScaffolderTest {

    @TempDir
    Path project;

    private final List<String> log = new ArrayList<>();

    private Path javaDir() {
        return project.resolve("src/main/java");
    }

    private Path resourceDir() {
        return project.resolve("src/main/resources");
    }

    private List<Path> scaffold(Framework framework, boolean force) throws IOException {
        return Scaffolder.write(Scaffolder.filesFor(framework, javaDir(), resourceDir(), "test:init"), force, log::add);
    }

    private static String read(Path file) throws IOException {
        return new String(Files.readAllBytes(file), StandardCharsets.UTF_8);
    }

    @Test
    void plainWritesOnlyTheMainClass() throws IOException {
        List<Path> written = scaffold(Framework.PLAIN, false);

        assertEquals(1, written.size());
        assertTrue(Files.exists(javaDir().resolve("sageactive4j/SageActiveExample.java")));
        assertFalse(Files.exists(resourceDir().resolve("sageactive4j.properties")));
    }

    @Test
    void servletAndJakartaUseTheirOwnNamespaces() throws IOException {
        scaffold(Framework.SERVLET, false);
        String servlet = read(javaDir().resolve("sageactive4j/SageActiveServlet.java"));
        assertTrue(servlet.contains("import javax.servlet.http.HttpServlet;"));
        assertTrue(servlet.contains("import io.github.josemodi97.sageactive4j.servlet.SageOAuthFlow;"));
        assertTrue(servlet.contains("Requires sageactive4j-servlet."));
        assertFalse(servlet.contains("jakarta"));

        scaffold(Framework.JAKARTA, true);
        String jakarta = read(javaDir().resolve("sageactive4j/SageActiveServlet.java"));
        assertTrue(jakarta.contains("import jakarta.servlet.http.HttpServlet;"));
        assertTrue(jakarta.contains("import io.github.josemodi97.sageactive4j.jakarta.SageOAuthFlow;"));
        assertFalse(jakarta.contains("javax"));
    }

    @Test
    void springBootGetsTheControllerAndAPropertiesFileWithoutSecrets() throws IOException {
        scaffold(Framework.SPRING_BOOT3, false);

        String controller = read(javaDir().resolve("sageactive4j/SageController.java"));
        assertTrue(controller.contains("@PropertySource(\"classpath:sageactive4j.properties\")"));
        assertTrue(controller.contains("Requires sageactive4j-spring-boot3-starter"));

        String properties = read(resourceDir().resolve("sageactive4j.properties"));
        assertTrue(properties.contains("sageactive4j.subscription-key=${SAGEACTIVE4J_SUBSCRIPTION_KEY:}"));
        assertTrue(properties.contains("sageactive4j.client-secret=${SAGEACTIVE4J_CLIENT_SECRET:}"));
        assertTrue(properties.contains("sageactive4j.oauth.enabled=true"));
    }

    @Test
    void noPlaceholderIsLeftUnrendered() throws IOException {
        for (Framework framework : Framework.values()) {
            for (Scaffolder.GeneratedFile file : Scaffolder.filesFor(framework, javaDir(), resourceDir(), "test:init")) {
                assertFalse(file.content.contains("{{"), framework + ": " + file.path);
                assertTrue(file.content.contains("Generated by test:init"), framework + ": " + file.path);
                assertFalse(file.content.contains("\r"), framework + ": " + file.path);
            }
        }
    }

    @Test
    void existingFilesAreLeftAloneUnlessForced() throws IOException {
        Path controller = javaDir().resolve("sageactive4j/SageController.java");
        Files.createDirectories(controller.getParent());
        Files.write(controller, "// mine\n".getBytes(StandardCharsets.UTF_8));

        List<Path> written = scaffold(Framework.SPRING_BOOT2, false);

        assertEquals("// mine\n", read(controller));
        assertEquals(1, written.size(), "the properties file is still written");
        assertTrue(log.get(0).contains("already exists - left untouched"), log.toString());

        written = scaffold(Framework.SPRING_BOOT2, true);

        assertEquals(2, written.size());
        assertTrue(read(controller).contains("public class SageController"));
        assertTrue(log.get(log.size() - 1).startsWith("Overwrote "), log.toString());
    }

    @Test
    void nextStepsAskForTheDependencyOnlyWhenItIsMissing() {
        List<String> missing = Scaffolder.nextSteps(Framework.JAKARTA, "0.1.0", false);
        assertEquals("Add the dependency io.github.josemodi97:sageactive4j-jakarta:0.1.0.", missing.get(0));

        List<String> declared = Scaffolder.nextSteps(Framework.JAKARTA, "0.1.0", true);
        assertFalse(declared.get(0).startsWith("Add the dependency"));
        assertTrue(Scaffolder.nextSteps(Framework.PLAIN, null, false).get(0).endsWith(":<version>."));
    }

    /**
     * Compiles each generated class for real, against this test's classpath,
     * which carries the sageactive4j adapters, both servlet APIs and Spring
     * Web. A wrong import or signature fails here, not in a user's project.
     * It compiles at the lowest Java release the framework's adapter
     * supports, so a newer JDK API in a template fails too.
     */
    @ParameterizedTest
    @EnumSource(Framework.class)
    void generatedJavaCompiles(Framework framework) throws IOException {
        scaffold(framework, false);
        List<String> args = new ArrayList<>();
        args.add("--release");
        args.add(framework == Framework.JAKARTA ? "11" : "8");
        args.add("-proc:none");
        // serial: servlets are Serializable; path: build tools list
        // classpath directories that may not exist yet.
        args.add("-Xlint:all,-serial,-path,-options");
        args.add("-Werror");
        args.add("-cp");
        args.add(testClasspath());
        args.add("-d");
        args.add(project.resolve("classes").toString());
        for (Scaffolder.GeneratedFile file : Scaffolder.filesFor(framework, javaDir(), resourceDir(), "test:init")) {
            if (file.path.toString().endsWith(".java")) {
                args.add(file.path.toString());
            }
        }

        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        ByteArrayOutputStream diagnostics = new ByteArrayOutputStream();
        int result = compiler.run(null, diagnostics, diagnostics, args.toArray(new String[0]));

        assertEquals(0, result, framework + " example failed to compile:\n" + diagnostics);
    }

    private static String testClasspath() {
        // Surefire may launch tests through a manifest-only jar; it still
        // publishes the real classpath under this property.
        String surefire = System.getProperty("surefire.test.class.path");
        return surefire != null && !surefire.isEmpty() ? surefire : System.getProperty("java.class.path");
    }
}
